version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: et_postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: saas_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    container_name: et_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
